In [15]:
from preprocess_kummu_gdp_v4 import download_file, preprocess_kummu_gdp_tif, KUMMU_V4_FILES
import os
ROOT_DIR = os.path.abspath(os.curdir)
gdp_path = ROOT_DIR + "\\" + 'GDP_data'
# 1. Download the 30 arc-sec total GDP file (1.4 GB — will take a few minutes)
tif_path = download_file(
    url=KUMMU_V4_FILES["rast_gdpTot_1990_2024_30arcsec.tif"],
    out_dir=gdp_path,
)

Already exists, skipping download: C:\Users\Bachirou\Documents\CREDIT_layer\GDP_data\rast_gdpTot_1990_2024_30arcsec.tif

In [10]:
import os
from extract_country_gdp_general import extract_country_gdp
from batch_extract_gdp import batch_extract_gdp

In [11]:
ROOT_DIR = os.path.abspath(os.curdir)
gdp_path = ROOT_DIR + "\\" + 'GDP_data'
da = extract_country_gdp("Guinea", 2024, gdp_path=gdp_path)

Resolved 'Guinea' -> ISO3 'GIN' (Guinea)
Loaded GIN ADM0 boundary: 1 feature(s), CRS=EPSG:4326
Guinea (GIN) 2024: 133349/586044 valid pixels, total GDP (sum of pixels) = 70,115,024,896
Saved: C:\Users\Bachirou\Documents\CREDIT_layer\GDP_data\GDP_PPP_2024_GIN.tif

In [7]:
from extract_country_gdp_general import extract_country_gdp

da = extract_country_gdp("Mali", 2024, gdp_path=gdp_path)

Resolved 'Mali' -> ISO3 'MLI' (Mali)
Mali (MLI) 2024: 223203/3524991 valid pixels, total GDP (sum of pixels) = 82,678,112,256
Saved: C:\Users\Bachirou\Documents\CREDIT_layer\GDP_data\GDP_PPP_2024_MLI_v4.tif

In [4]:
from extract_country_gdp_general import extract_country_gdp

da = extract_country_gdp("Mali", 2024, gdp_path=gdp_path, mask_zero=True, zero_value=0)

Resolved 'Mali' -> ISO3 'MLI' (Mali)
Mali (MLI) 2024: 223203/3524991 valid pixels, total GDP (sum of pixels) = 82,678,112,256
Saved: C:\Users\Bachirou\Documents\CREDIT_layer\GDP_data\GDP_PPP_2024_MLI_v4.tif

In [6]:
da = extract_country_gdp("Mali", 2024, gdp_path=gdp_path, mask_zero=True, zero_value=0)

Resolved 'Mali' -> ISO3 'MLI' (Mali)
Mali (MLI) 2024: 223203/3524991 valid pixels, total GDP (sum of pixels) = 82,678,112,256
Saved: C:\Users\Bachirou\Documents\CREDIT_layer\GDP_data\GDP_PPP_2024_MLI_v4.tif

In [8]:
from extract_poverty_data_hdx import extract_country_mpi

df_niger = extract_country_mpi("Niger")   # saves to CREDIT_layer/poverty_data/
df_niger.head()

,Country ISO3,Admin 1 PCode,Admin 1 Name,MPI,Headcount Ratio,Intensity of Deprivation,Vulnerable to Poverty,In Severe Poverty,Survey,Start Date,End Date
0,AFG,NaN,NaN,0.3603,64.8829,55.5317,19.8961,39.1051,MICS,2022-01-01 00:00:00+00:00,2023-12-31 00:00:00+00:00
1,AFG,AF01,Kabul,0.1268,27.9088,45.4448,34.6170,7.7371,MICS,2022-01-01 00:00:00+00:00,2023-12-31 00:00:00+00:00
2,AFG,AF02,Kapisa,0.4199,76.7438,54.7140,17.6739,44.9334,MICS,2022-01-01 00:00:00+00:00,2023-12-31 00:00:00+00:00
3,AFG,AF03,Parwan,0.3021,57.7282,52.3311,27.8219,29.0427,MICS,2022-01-01 00:00:00+00:00,2023-12-31 00:00:00+00:00
4,AFG,AF04,Wardak,0.3393,64.7870,52.3707,24.8975,35.2280,MICS,2022-01-01 00:00:00+00:00,2023-12-31 00:00:00+00:00

In [2]:
from extract_poverty_data_hdx import extract_country_tabular

df_niger = extract_country_tabular("Guinea")
df_niger.head()

[OK] Downloaded Guinea_Guinea_MPI_and_Partial_Indices.csv

,Country ISO3,Admin 1 PCode,Admin 1 Name,MPI,Headcount Ratio,Intensity of Deprivation,Vulnerable to Poverty,In Severe Poverty,Survey,Start Date,End Date
0,GIN,NaN,NaN,0.3732,66.2111,56.3684,16.4050,43.5149,DHS,2018-01-01 00:00:00+00:00,2018-12-31 23:59:59+00:00
1,GIN,GN001,Boké,0.4221,71.6486,58.9099,12.2998,51.4237,DHS,2018-01-01 00:00:00+00:00,2018-12-31 23:59:59+00:00
2,GIN,GN002,Conakry,0.0632,14.2916,44.2306,33.8578,3.7915,DHS,2018-01-01 00:00:00+00:00,2018-12-31 23:59:59+00:00
3,GIN,GN003,Faranah,0.4888,82.7203,59.0921,12.2533,62.2183,DHS,2018-01-01 00:00:00+00:00,2018-12-31 23:59:59+00:00
4,GIN,GN004,Kankan,0.4171,75.7174,55.0910,13.5434,46.7549,DHS,2018-01-01 00:00:00+00:00,2018-12-31 23:59:59+00:00

In [9]:
from extract_poverty_data_hdx import extract_country_data
result = extract_country_data("Guinea")

[SKIP] Guinea_Guinea_MPI_and_Partial_Indices.csv already exists, not re-downloading.
[OK] Downloaded Guinea_gin_admin_boundaries.shp.zip.zip
[OK] Extracted to C:\Users\Bachirou\Documents\CREDIT_layer\poverty_data\shapefile\Guinea_gin_admin_boundaries.shp.zip